services:
  - type: web
    name: optica-api-productos
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      flask db upgrade
    startCommand: gunicorn run:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: optica-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true

databases:
  - name: optica-db
    databaseName: optica
    plan: free
    postgresMajorVersion: 14